- hosts: servers
  roles:
    - base
    - hosts
    - gai
    - sysctl
    - sudo
    - root
    - motd
    - firewall
    - docker
    - users
    - traefik

- hosts: gefjon
  roles:
    - minio
    - downloads
